#!/bin/bash

# Check if argument is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <subdirectory_with_file> <number_of_threads> "
    exit 1
fi

# Set the filename from the argument
FILENAME="$1"
cd "/home/admin2/BerkeleyUPCMag/src/$FILENAME"
# Compile the C file
#gcc -o "$FILENAME.exe" "$FILENAME.c" ../common-functions/common-functions.c
/home/admin1/BUPC/opt/upcc -T $2 -o "$FILENAME.exe" "$FILENAME.c" #../common-functions/common-functions.c
if [ $? -ne 0 ]; then
    echo "Compilation failed."
    exit 1
fi
clear
# Run the compiled executable
#./"$FILENAME.exe"
/home/admin1/BUPC/opt/upcrun -backtrace -n $2 "$FILENAME.exe"
